// Generated by CoffeeScript 1.4.0
(function() {
  var buster;

  buster = (typeof window !== "undefined" && window !== null ? window.buster : void 0) != null ? window.buster : require("buster");

}).call(this);
