// Generated by CoffeeScript 1.4.0
(function() {
  var tee,
    __slice = [].slice;

  exports.tee = tee = function(val, fns) {
    var fn, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = fns.length; _i < _len; _i++) {
      fn = fns[_i];
      _results.push(fn(val));
    }
    return _results;
  };

  exports.mktee = function() {
    var fns;
    fns = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return function(val) {
      return tee(val, fns);
    };
  };

}).call(this);
